before_install:
  - sudo apt-get install -y libx11-dev
  - sudo apt-get install -y libxtst-dev
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
